// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import { restart } from "nodemon";
import clientPromise from "../../../util/mongodb";
const ObjectId = require('mongodb').ObjectId;

export default async function handler(req, res) {
  // switch the methods
    switch (req.method) {
        case 'GET': {
            return getCourses(req, res);
        }
        case 'POST': {
            return addNewCategory(req, res);
        }
    }
}

async function getCourses(req,res){
    try {
        // connect to the database
        const client = await clientPromise
        const db = client.db("ProjectPortforlio");
        // fetch the courses
        const courses = await db
            .collection('courses')
            .find({})
            .sort({ published: -1 })
            .toArray();
        // return the courses
        return res.json({
            message: JSON.parse(JSON.stringify(courses)),
            success: true,
        });
    } catch (error) {
        // return the error
        return res.json({
            message: new Error(error).message,
            success: false,
        });
    }
}

async function addNewCategory(req, res) {
    try {
        const data = req.body;

        // connect to the database
        const client = await clientPromise
        const db = client.db("ProjectPortforlio");
        // fetch the courses
        const courses = db.collection('new-categories');

        // insertOne returns an autogenerated id
        const result = await courses.insertOne(data)
        console.log(result)

        // return the message
        res.status(201).json({
            message: "New Category Inserted!",
            success: true,
        });
    } catch (error) {
        return res.json({
            message: new Error(error).message,
            success: false,
        })
    }
}